import { ProgressStepsType, ServiceType } from "@/types";

const services: ServiceType[] = [
  { id: "svc_001", name: "Pendirian PT" },
  { id: "svc_002", name: "PT + Izin" },
  { id: "svc_003", name: "PT + Izin + Virtual Office" },
  { id: "svc_004", name: "PT + Izin + Virtual Office + PKP" },
  { id: "svc_005", name: "PT + Izin + Virtual Office SCBD" },
  { id: "svc_006", name: "PT + Izin + Virtual Office SCBD + PKP" },
  { id: "svc_007", name: "Pendirian CV" },
  { id: "svc_008", name: "CV + Izin" },
  { id: "svc_009", name: "CV + Izin + Virtual Office" },
  { id: "svc_010", name: "CV + Izin + Virtual Office SCBD" },
  { id: "svc_011", name: "CV + Izin + Virtual Office + PKP" },
  { id: "svc_012", name: "CV + Izin + Virtual Office SCBD + PKP" },
  { id: "svc_013", name: "Pendirian PT Perorangan" },
  { id: "svc_014", name: "PT Perorangan + Izin" },
  { id: "svc_015", name: "PT Perorangan + Izin + Virtual Office" },
  { id: "svc_016", name: "PT Perorangan + Izin + Virtual Office SCBD" },
  { id: "svc_017", name: "PT Perorangan + Izin + Virtual Office + PKP" },
  { id: "svc_018", name: "PT Perorangan + Izin + Virtual Office SCBD + PKP" },
  { id: "svc_019", name: "Pendirian PMA" },
  { id: "svc_020", name: "PMA + Izin" },
  { id: "svc_021", name: "PMA + Izin + Virtual Office" },
  { id: "svc_022", name: "PMA + Izin + Virtual Office SCBD" },
  { id: "svc_023", name: "PMA + Izin + Virtual Office + PKP" },
  { id: "svc_024", name: "PMA + Izin + Virtual Office SCBD + PKP" },
  { id: "svc_025", name: "Pendirian Firma" },
  { id: "svc_026", name: "Firma + Izin" },
  { id: "svc_027", name: "Firma + Izin + Virtual Office" },
  { id: "svc_028", name: "Firma + Izin + Virtual Office SCBD" },
  { id: "svc_029", name: "Firma + Izin + Virtual Office + PKP" },
  { id: "svc_030", name: "Firma + Izin + Virtual Office SCBD + PKP" },
  { id: "svc_031", name: "Pendirian Persekutuan Perdata" },
  { id: "svc_032", name: "Persekutuan Perdata + Izin" },
  { id: "svc_033", name: "Persekutuan Perdata + Izin + Virtual Office" },
  { id: "svc_034", name: "Persekutuan Perdata + Izin + Virtual Office SCBD" },
  { id: "svc_035", name: "Persekutuan Perdata + Izin + Virtual Office + PKP" },
  {
    id: "svc_036",
    name: "Persekutuan Perdata + Izin + Virtual Office SCBD + PKP",
  },
  { id: "svc_037", name: "Pendirian Perkumpulan" },
  { id: "svc_038", name: "Perkumpulan + Izin" },
  { id: "svc_039", name: "Pendirian Yayasan" },
  { id: "svc_040", name: "Pendirian Yayasan + Izin" },
  { id: "svc_041", name: "Jasa Pengurusan NIB & OSS" },
  { id: "svc_042", name: "Jasa Pengurusan PKP" },
  { id: "svc_043", name: "Pengurusan SPPL" },
  { id: "svc_044", name: "Pengurusan SLHS (Sertifikat Laik Higiene Sanitasi)" },
  { id: "svc_045", name: "Sertifikat Higiene Sanitasi Penjamah Pangan" },
  { id: "svc_046", name: "Sertifikat Higiene Sanitasi Penanggung Jawab Usaha" },
  { id: "svc_047", name: "[ALL IN] Izin Restoran" },
  { id: "svc_048", name: "Izin Konstruksi / SIUJK" },
  { id: "svc_049", name: "Pengurusan PSE Domestik" },
  { id: "svc_050", name: "Pengurusan PSE Asing" },
  { id: "svc_051", name: "Pengurusan K3L" },
  { id: "svc_052", name: "[ALL IN] Pengurusan K3L & Uji Lab" },
  { id: "svc_053", name: "Pengurusan Izin KITAS" },
  { id: "svc_054", name: "Jasa Pendaftaran Merek" },
  { id: "svc_055", name: "Perjanjian Pisah Harta Pra Menikah" },
  { id: "svc_056", name: "Pendaftaran Pisah Harta KUA/Dukcapil Jakarta" },
  { id: "svc_057", name: "[ALL IN] Perjanjian Pisah Harta" },
  { id: "svc_058", name: "PT - Penonaktifan Perusahaan" },
  { id: "svc_059", name: "PT - Tutup Perusahaan (Non-Likuidasi)" },
  { id: "svc_060", name: "PT Po - Penonaktifan Perusahaan" },
  { id: "svc_061", name: "CV - Penonaktifan Perusahaan" },
  { id: "svc_062", name: "PMA - Penonaktifan Perusahaan" },
  { id: "svc_063", name: "PMA - Tutup Perusahaan (Non-Likuidasi)" },
  { id: "svc_064", name: "Perubahan Anggaran Dasar PT" },
  { id: "svc_065", name: "Perubahan Anggaran Dasar CV" },
  { id: "svc_066", name: "Akta Jual Beli Saham (Notariil)" },
  { id: "svc_067", name: "Virtual Office Jakarta" },
  { id: "svc_068", name: "Virtual Office Premium @SCBD" },
];

const progressSteps: ProgressStepsType[] = [
  { id: "s-1", title: "Konsultasi Awal", progress: 15 },
  { id: "s-2", title: "Pengumpulan & Persiapan Dokumen", progress: 30 },
  { id: "s-3", title: "Review & Validasi Dokumen", progress: 40},
  { id: "s-4", title: "Proses Legal/Formalitas", progress: 55},
  { id: "s-5", title: "Verifikasi & Approval Instansi", progress: 70 },
  { id: "s-6", title: "Dokumen Diterbitkan", progress: 85 },
  { id: "s-7", title: "Finalisasi & Penyerahan ke Klien", progress: 100 },
];

export { services, progressSteps };
